pipeline {
    agent any 
    stages {
        stage('Login') {
            steps {
                    withCredentials([string(credentialsId: 'DOCKER_HUB_PASSWORD', variable: 'PASSWORD')]){
                    sh 'docker login -u astr1k -p $PASSWORD'
                    }
            }
        }
        stage('Build') { 
            steps {
                dir ('docker') {
                    sh 'pwd'
                    sh 'ls -la /var/jenkins_home/workspace/Proj'
              sh 'docker build -t astr1k/myproj:latest .'
            }
        }
    }
        stage('Deploy') { 
            steps {
                
                sh 'docker push astr1k/myproj:latest' 
            }
        }       
    }
  }
